// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU9q74Weajl0pBRSAAd2GTEv7xf4XpaQ8',
    appId: '1:725615374942:web:ffb8dd780313bf16c93acf',
    messagingSenderId: '725615374942',
    projectId: 'leavemanagementsystem-d7c70',
    authDomain: 'leavemanagementsystem-d7c70.firebaseapp.com',
    storageBucket: 'leavemanagementsystem-d7c70.firebasestorage.app',
    measurementId: 'G-GNML5ZLVBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW_ww1Ibc8fZZtq67Yfg_ZTUjmB0ezMfk',
    appId: '1:725615374942:android:3f97bc6ff9f67459c93acf',
    messagingSenderId: '725615374942',
    projectId: 'leavemanagementsystem-d7c70',
    storageBucket: 'leavemanagementsystem-d7c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYR9s4twHWLj7_8-zO8tfZmQZ06L0fMAY',
    appId: '1:725615374942:ios:0283f323b38b66b7c93acf',
    messagingSenderId: '725615374942',
    projectId: 'leavemanagementsystem-d7c70',
    storageBucket: 'leavemanagementsystem-d7c70.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYR9s4twHWLj7_8-zO8tfZmQZ06L0fMAY',
    appId: '1:725615374942:ios:0283f323b38b66b7c93acf',
    messagingSenderId: '725615374942',
    projectId: 'leavemanagementsystem-d7c70',
    storageBucket: 'leavemanagementsystem-d7c70.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU9q74Weajl0pBRSAAd2GTEv7xf4XpaQ8',
    appId: '1:725615374942:web:230176f0d953b086c93acf',
    messagingSenderId: '725615374942',
    projectId: 'leavemanagementsystem-d7c70',
    authDomain: 'leavemanagementsystem-d7c70.firebaseapp.com',
    storageBucket: 'leavemanagementsystem-d7c70.firebasestorage.app',
    measurementId: 'G-E9BZDV08JF',
  );
}
